# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartWalker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #Turn off warnings for frameworks
  inhibit_all_warnings!

  # Pods for SmartWalker
  pod 'BEMSimpleLineGraph', :git => 'https://github.com/Boris-Em/BEMSimpleLineGraph.git', :branch => 'feature'
end
